// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto

package ai.yunxi.im.common.protocol;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageProtocolOrBuilder extends
          // @@protoc_insertion_point(interface_extends:protocol.MessageProtocol)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <pre>
     * 消息数组
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 消息数组
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
    getContentBytes();

    /**
     * <pre>
     * timestmap
     * </pre>
     *
     * <code>int64 time = 3;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <code>bool ack = 4;</code>
     * @return The ack.
     */
    boolean getAck();

    /**
     * <code>int32 command = 5;</code>
     * @return The command.
     */
    int getCommand();

    /**
     * <code>int32 userId = 6;</code>
     * @return The userId.
     */
    int getUserId();
  }
  /**
   * Protobuf type {@code protocol.MessageProtocol}
   */
  public  static final class MessageProtocol extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:protocol.MessageProtocol)
          MessageProtocolOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use MessageProtocol.newBuilder() to construct.
    private MessageProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageProtocol() {
      id_ = "";
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new MessageProtocol();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageProtocol(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 24: {

              time_ = input.readInt64();
              break;
            }
            case 32: {

              ack_ = input.readBool();
              break;
            }
            case 40: {

              command_ = input.readInt32();
              break;
            }
            case 48: {

              userId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return ai.yunxi.im.common.protocol.MessageProto.internal_static_protocol_MessageProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return ai.yunxi.im.common.protocol.MessageProto.internal_static_protocol_MessageProtocol_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      ai.yunxi.im.common.protocol.MessageProto.MessageProtocol.class, ai.yunxi.im.common.protocol.MessageProto.MessageProtocol.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
    getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 消息数组
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息数组
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
    getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <pre>
     * timestmap
     * </pre>
     *
     * <code>int64 time = 3;</code>
     * @return The time.
     */
    public long getTime() {
      return time_;
    }

    public static final int ACK_FIELD_NUMBER = 4;
    private boolean ack_;
    /**
     * <code>bool ack = 4;</code>
     * @return The ack.
     */
    public boolean getAck() {
      return ack_;
    }

    public static final int COMMAND_FIELD_NUMBER = 5;
    private int command_;
    /**
     * <code>int32 command = 5;</code>
     * @return The command.
     */
    public int getCommand() {
      return command_;
    }

    public static final int USERID_FIELD_NUMBER = 6;
    private int userId_;
    /**
     * <code>int32 userId = 6;</code>
     * @return The userId.
     */
    public int getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (time_ != 0L) {
        output.writeInt64(3, time_);
      }
      if (ack_ != false) {
        output.writeBool(4, ack_);
      }
      if (command_ != 0) {
        output.writeInt32(5, command_);
      }
      if (userId_ != 0) {
        output.writeInt32(6, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(3, time_);
      }
      if (ack_ != false) {
        size += com.google.protobuf.CodedOutputStream
                .computeBoolSize(4, ack_);
      }
      if (command_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(5, command_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(6, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ai.yunxi.im.common.protocol.MessageProto.MessageProtocol)) {
        return super.equals(obj);
      }
      ai.yunxi.im.common.protocol.MessageProto.MessageProtocol other = (ai.yunxi.im.common.protocol.MessageProto.MessageProtocol) obj;

      if (!getId()
              .equals(other.getId())) return false;
      if (!getContent()
              .equals(other.getContent())) return false;
      if (getTime()
              != other.getTime()) return false;
      if (getAck()
              != other.getAck()) return false;
      if (getCommand()
              != other.getCommand()) return false;
      if (getUserId()
              != other.getUserId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTime());
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getAck());
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ai.yunxi.im.common.protocol.MessageProto.MessageProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.MessageProtocol}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protocol.MessageProtocol)
            ai.yunxi.im.common.protocol.MessageProto.MessageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return ai.yunxi.im.common.protocol.MessageProto.internal_static_protocol_MessageProtocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return ai.yunxi.im.common.protocol.MessageProto.internal_static_protocol_MessageProtocol_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ai.yunxi.im.common.protocol.MessageProto.MessageProtocol.class, ai.yunxi.im.common.protocol.MessageProto.MessageProtocol.Builder.class);
      }

      // Construct using ai.yunxi.im.common.protocol.MessageProto.MessageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        content_ = "";

        time_ = 0L;

        ack_ = false;

        command_ = 0;

        userId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return ai.yunxi.im.common.protocol.MessageProto.internal_static_protocol_MessageProtocol_descriptor;
      }

      @java.lang.Override
      public ai.yunxi.im.common.protocol.MessageProto.MessageProtocol getDefaultInstanceForType() {
        return ai.yunxi.im.common.protocol.MessageProto.MessageProtocol.getDefaultInstance();
      }

      @java.lang.Override
      public ai.yunxi.im.common.protocol.MessageProto.MessageProtocol build() {
        ai.yunxi.im.common.protocol.MessageProto.MessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ai.yunxi.im.common.protocol.MessageProto.MessageProtocol buildPartial() {
        ai.yunxi.im.common.protocol.MessageProto.MessageProtocol result = new ai.yunxi.im.common.protocol.MessageProto.MessageProtocol(this);
        result.id_ = id_;
        result.content_ = content_;
        result.time_ = time_;
        result.ack_ = ack_;
        result.command_ = command_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ai.yunxi.im.common.protocol.MessageProto.MessageProtocol) {
          return mergeFrom((ai.yunxi.im.common.protocol.MessageProto.MessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ai.yunxi.im.common.protocol.MessageProto.MessageProtocol other) {
        if (other == ai.yunxi.im.common.protocol.MessageProto.MessageProtocol.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getAck() != false) {
          setAck(other.getAck());
        }
        if (other.getCommand() != 0) {
          setCommand(other.getCommand());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        ai.yunxi.im.common.protocol.MessageProto.MessageProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ai.yunxi.im.common.protocol.MessageProto.MessageProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
      getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 消息数组
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息数组
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
      getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息数组
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息数组
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息数组
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       * timestmap
       * </pre>
       *
       * <code>int64 time = 3;</code>
       * @return The time.
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       * timestmap
       * </pre>
       *
       * <code>int64 time = 3;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {

        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * timestmap
       * </pre>
       *
       * <code>int64 time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {

        time_ = 0L;
        onChanged();
        return this;
      }

      private boolean ack_ ;
      /**
       * <code>bool ack = 4;</code>
       * @return The ack.
       */
      public boolean getAck() {
        return ack_;
      }
      /**
       * <code>bool ack = 4;</code>
       * @param value The ack to set.
       * @return This builder for chaining.
       */
      public Builder setAck(boolean value) {

        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool ack = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAck() {

        ack_ = false;
        onChanged();
        return this;
      }

      private int command_ ;
      /**
       * <code>int32 command = 5;</code>
       * @return The command.
       */
      public int getCommand() {
        return command_;
      }
      /**
       * <code>int32 command = 5;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(int value) {

        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 command = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {

        command_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 6;</code>
       * @return The userId.
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 6;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {

        userId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.MessageProtocol)
    }

    // @@protoc_insertion_point(class_scope:protocol.MessageProtocol)
    private static final ai.yunxi.im.common.protocol.MessageProto.MessageProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ai.yunxi.im.common.protocol.MessageProto.MessageProtocol();
    }

    public static ai.yunxi.im.common.protocol.MessageProto.MessageProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageProtocol>
            PARSER = new com.google.protobuf.AbstractParser<MessageProtocol>() {
      @java.lang.Override
      public MessageProtocol parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageProtocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ai.yunxi.im.common.protocol.MessageProto.MessageProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_protocol_MessageProtocol_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_protocol_MessageProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\022MessageProto.proto\022\010protocol\"j\n\017Messag" +
                    "eProtocol\022\n\n\002id\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\014" +
                    "\n\004time\030\003 \001(\003\022\013\n\003ack\030\004 \001(\010\022\017\n\007command\030\005 \001" +
                    "(\005\022\016\n\006userId\030\006 \001(\005B+\n\033ai.yunxi.im.common" +
                    ".protocolB\014MessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_protocol_MessageProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_MessageProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_protocol_MessageProtocol_descriptor,
            new java.lang.String[] { "Id", "Content", "Time", "Ack", "Command", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
